name: Bump version

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'package.json'
    tags-ignore:
      - 'v*.*.*'

env:
  NODE_AUTH_TOKEN: ${{ secrets.OSOME_BOT_TOKEN }}

jobs:
  minor:
    name: 'Bump minor version'
    runs-on: ubuntu-latest
    if: github.actor != 'osome-bot'

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.OSOME_BOT_TOKEN }}

    - id: should_skip_ci
      uses: osomepteltd/actions/packages/should-skip-ci@master
      with:
        token: ${{ secrets.OSOME_BOT_TOKEN }}

    - if: ${{ !fromJson(steps.should_skip_ci.outputs.skip_ci) }}
      uses: osomepteltd/actions/packages/bump-version@master
      with:
        token: ${{ secrets.OSOME_BOT_TOKEN }}
