name: Bump version

on:
  repository_dispatch:
    types:
      - deploy

env:
  NODE_AUTH_TOKEN: ${{ secrets.OSOME_BOT_TOKEN }}

jobs:
  minor:
    name: 'Bump minor version'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.OSOME_BOT_TOKEN }}

    - uses: osomepteltd/actions/packages/bump-version@master
      with:
        token: ${{ secrets.OSOME_BOT_TOKEN }}
